### ISSUE TITLE
Morning session feedback

### ISSUE THREAD

**Issue by J-C-S-V** [fpsapc/MicroverseStudentProject1#4]
- Use more specific class names: Using more specific class names can make the code more readable and easier to understand. For example, instead of using "footer" as a class name, you could use "site-footer" or "page-footer" to provide more context.
- Use consistent naming conventions: Make sure to use a consistent naming convention for class names, such as camelCase or kebab-case. This can help make your code more readable and maintainable.
- Consolidate styles: Consider consolidating styles that are repeated across multiple classes. For example, the "cursor" and "padding" properties could be defined in a single class and applied to multiple elements.
- Capitalized the first letter when committing.
- It would be better not to use vh or vw unless there is a good reason.

**Comment by Alejandroq12** [comment]
In additon:
- According to the HTML5 specification, the <main> element should be used to represent the main content of the document.
While it is technically possible to use <main> for more than one section, it is generally recommended to reserve <main> for the main content of the document and use other elements for additional sections of the content.

**Comment by fpsapc** [comment]
Thanks for suggestions.
